apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secret-provider
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "backend-secrets"
        objectType: "secretsmanager"
